/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SongsSongIdRouteImport } from './routes/songs.$songId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiBlobUploadRouteImport } from './routes/api/blob/upload'
import { Route as ApiBlobSignedUrlRouteImport } from './routes/api/blob/signed-url'
import { Route as ApiBlobDeleteRouteImport } from './routes/api/blob/delete'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsSongIdRoute = SongsSongIdRouteImport.update({
  id: '/songs/$songId',
  path: '/songs/$songId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlobUploadRoute = ApiBlobUploadRouteImport.update({
  id: '/api/blob/upload',
  path: '/api/blob/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlobSignedUrlRoute = ApiBlobSignedUrlRouteImport.update({
  id: '/api/blob/signed-url',
  path: '/api/blob/signed-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlobDeleteRoute = ApiBlobDeleteRouteImport.update({
  id: '/api/blob/delete',
  path: '/api/blob/delete',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/songs/$songId': typeof SongsSongIdRoute
  '/api/blob/delete': typeof ApiBlobDeleteRoute
  '/api/blob/signed-url': typeof ApiBlobSignedUrlRoute
  '/api/blob/upload': typeof ApiBlobUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/songs/$songId': typeof SongsSongIdRoute
  '/api/blob/delete': typeof ApiBlobDeleteRoute
  '/api/blob/signed-url': typeof ApiBlobSignedUrlRoute
  '/api/blob/upload': typeof ApiBlobUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/songs/$songId': typeof SongsSongIdRoute
  '/api/blob/delete': typeof ApiBlobDeleteRoute
  '/api/blob/signed-url': typeof ApiBlobSignedUrlRoute
  '/api/blob/upload': typeof ApiBlobUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/callback'
    | '/songs/$songId'
    | '/api/blob/delete'
    | '/api/blob/signed-url'
    | '/api/blob/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/songs/$songId'
    | '/api/blob/delete'
    | '/api/blob/signed-url'
    | '/api/blob/upload'
  id:
    | '__root__'
    | '/'
    | '/auth/callback'
    | '/songs/$songId'
    | '/api/blob/delete'
    | '/api/blob/signed-url'
    | '/api/blob/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  SongsSongIdRoute: typeof SongsSongIdRoute
  ApiBlobDeleteRoute: typeof ApiBlobDeleteRoute
  ApiBlobSignedUrlRoute: typeof ApiBlobSignedUrlRoute
  ApiBlobUploadRoute: typeof ApiBlobUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$songId': {
      id: '/songs/$songId'
      path: '/songs/$songId'
      fullPath: '/songs/$songId'
      preLoaderRoute: typeof SongsSongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blob/upload': {
      id: '/api/blob/upload'
      path: '/api/blob/upload'
      fullPath: '/api/blob/upload'
      preLoaderRoute: typeof ApiBlobUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blob/signed-url': {
      id: '/api/blob/signed-url'
      path: '/api/blob/signed-url'
      fullPath: '/api/blob/signed-url'
      preLoaderRoute: typeof ApiBlobSignedUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blob/delete': {
      id: '/api/blob/delete'
      path: '/api/blob/delete'
      fullPath: '/api/blob/delete'
      preLoaderRoute: typeof ApiBlobDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  SongsSongIdRoute: SongsSongIdRoute,
  ApiBlobDeleteRoute: ApiBlobDeleteRoute,
  ApiBlobSignedUrlRoute: ApiBlobSignedUrlRoute,
  ApiBlobUploadRoute: ApiBlobUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
